import type {
  CardCaseContent,
  InvestigationCard,
} from "./types";

const CASE_ID = "case.the-pain-that-moved";
const VARIANT_ID = "variant.classic";
const APPENDICITIS = "diagnosis.appendicitis";
const STOMACH_INFECTION = "diagnosis.gastroenteritis";
const URINARY_INFECTION = "diagnosis.urinary-tract-infection";
const KIDNEY_STONE = "diagnosis.kidney-stone";

const compatibility = { caseIds: [CASE_ID], variantIds: [VARIANT_ID] };

const cards: InvestigationCard[] = [
  {
    id: "card.ask.pain-movement",
    displayName: "Did the pain move?",
    category: "ask",
    description: "Ask how the pain's location changed.",
    iconKey: "chat-arrow",
    compatibility,
    result: { type: "reveal_clue", clueId: "clue.pain-migrated-lower-right" },
    visibility: "private",
    duplicatePolicy: "allow",
    copies: 2,
    caseValue: "meaningful",
    rarity: "common",
    beginnerHint: "A changing location can separate the choices.",
  },
  {
    id: "card.ask.appetite",
    displayName: "Any appetite?",
    category: "ask",
    description: "Ask whether Jordan feels like eating.",
    iconKey: "chat-apple",
    compatibility,
    result: { type: "reveal_clue", clueId: "clue.loss-of-appetite" },
    visibility: "private",
    duplicatePolicy: "allow",
    copies: 2,
    caseValue: "meaningful",
    rarity: "common",
    beginnerHint: "Small details can reinforce a larger pattern.",
  },
  {
    id: "card.ask.diarrhea",
    displayName: "Any diarrhea?",
    category: "ask",
    description: "Ask about a common stomach-infection symptom.",
    iconKey: "chat-question",
    compatibility,
    result: { type: "reveal_clue", clueId: "clue.no-diarrhea" },
    visibility: "private",
    duplicatePolicy: "allow",
    copies: 2,
    caseValue: "meaningful",
    rarity: "common",
    beginnerHint: "A missing symptom can make one choice less likely.",
  },
  {
    id: "card.ask.urinary-symptoms",
    displayName: "Any urinary trouble?",
    category: "ask",
    description: "Ask whether urination burns or happens more often.",
    iconKey: "chat-water",
    compatibility,
    result: { type: "reveal_clue", clueId: "clue.no-urinary-symptoms" },
    visibility: "private",
    duplicatePolicy: "allow",
    copies: 2,
    caseValue: "meaningful",
    rarity: "common",
  },
  {
    id: "card.check.temperature",
    displayName: "Check temperature",
    category: "check",
    description: "See whether Jordan has a fever.",
    iconKey: "thermometer",
    compatibility,
    result: { type: "reveal_clue", clueId: "clue.temperature-38" },
    visibility: "public",
    duplicatePolicy: "allow",
    copies: 2,
    caseValue: "meaningful",
    rarity: "common",
  },
  {
    id: "card.check.abdomen",
    displayName: "Examine the abdomen",
    category: "check",
    description: "Check where the stomach area is most tender.",
    iconKey: "hands-check",
    compatibility,
    result: { type: "reveal_clue", clueId: "clue.lower-right-tenderness" },
    visibility: "private",
    duplicatePolicy: "allow",
    copies: 2,
    caseValue: "meaningful",
    rarity: "common",
    beginnerHint: "The location of tenderness can be especially useful.",
  },
  {
    id: "card.check.hydration",
    displayName: "Check hydration",
    category: "check",
    description: "Look for simple signs that Jordan needs fluids.",
    iconKey: "water-drop",
    compatibility,
    result: { type: "reveal_clue", clueId: "clue.mild-dehydration" },
    visibility: "private",
    duplicatePolicy: "allow",
    copies: 2,
    caseValue: "irrelevant",
    rarity: "common",
    beginnerHint: "Helpful context is not always useful for solving the mystery.",
  },
  {
    id: "card.check.pain-again",
    displayName: "Recheck the pain",
    category: "check",
    description: "Check whether the pain is still focused in one place.",
    iconKey: "location-check",
    compatibility,
    result: { type: "reveal_clue", clueId: "clue.pain-remains-localized" },
    visibility: "private",
    duplicatePolicy: "allow",
    copies: 2,
    caseValue: "meaningful",
    rarity: "common",
  },
  {
    id: "card.test.blood",
    displayName: "Blood test",
    category: "test",
    description: "Look for a simple sign of inflammation.",
    iconKey: "test-tube",
    compatibility,
    result: { type: "reveal_clue", clueId: "clue.white-count-elevated" },
    visibility: "private",
    duplicatePolicy: "unique_per_deck",
    copies: 1,
    caseValue: "meaningful",
    rarity: "uncommon",
  },
  {
    id: "card.test.urine",
    displayName: "Urine test",
    category: "test",
    description: "Look for signs of a urinary infection.",
    iconKey: "sample-cup",
    compatibility,
    result: { type: "reveal_clue", clueId: "clue.urinalysis-no-infection-support" },
    visibility: "private",
    duplicatePolicy: "unique_per_deck",
    copies: 1,
    caseValue: "meaningful",
    rarity: "uncommon",
  },
  {
    id: "card.test.ultrasound",
    displayName: "Ultrasound",
    category: "test",
    description: "Use a picture-based test to look for a strong clue.",
    iconKey: "ultrasound",
    compatibility,
    result: { type: "reveal_clue", clueId: "clue.ultrasound-consistent-appendicitis" },
    visibility: "private",
    duplicatePolicy: "unique_per_deck",
    copies: 1,
    caseValue: "meaningful",
    rarity: "rare",
    beginnerHint: "Tests can be powerful, but they are less common in the deck.",
  },
  {
    id: "card.special.draw-two",
    displayName: "Draw Two, Keep One",
    category: "special",
    description: "Draw two cards. Keep the more useful option.",
    iconKey: "cards-plus",
    compatibility,
    result: { type: "special", effect: { type: "draw_two_keep_one" } },
    visibility: "private",
    duplicatePolicy: "unique_per_deck",
    copies: 1,
    caseValue: "meaningful",
    rarity: "uncommon",
  },
  {
    id: "card.special.swap-one",
    displayName: "Swap One Card",
    category: "special",
    description: "Replace one card that is not helping your investigation.",
    iconKey: "cards-swap",
    compatibility,
    result: { type: "special", effect: { type: "swap_one_card" } },
    visibility: "private",
    duplicatePolicy: "unique_per_deck",
    copies: 1,
    caseValue: "meaningful",
    rarity: "uncommon",
  },
  {
    id: "card.special.repeat-check",
    displayName: "Repeat Check",
    category: "special",
    description: "Repeat your most recent Check card.",
    iconKey: "repeat-check",
    compatibility,
    result: { type: "special", effect: { type: "repeat_check" } },
    visibility: "private",
    duplicatePolicy: "unique_per_deck",
    copies: 1,
    caseValue: "meaningful",
    rarity: "uncommon",
  },
  {
    id: "card.special.second-opinion",
    displayName: "Second Opinion",
    category: "special",
    description: "Receive one extra private clue.",
    iconKey: "two-bubbles",
    compatibility,
    result: {
      type: "special",
      effect: { type: "second_opinion", clueId: "clue.no-urinary-symptoms" },
    },
    visibility: "private",
    duplicatePolicy: "unique_per_deck",
    copies: 1,
    caseValue: "meaningful",
    rarity: "uncommon",
  },
  {
    id: "card.special.share-clue",
    displayName: "Share a Clue",
    category: "special",
    description: "Reveal one authored clue to the whole room.",
    iconKey: "share-spark",
    compatibility,
    result: {
      type: "special",
      effect: { type: "share_clue", clueId: "clue.no-diarrhea" },
    },
    visibility: "public",
    duplicatePolicy: "unique_per_deck",
    copies: 1,
    caseValue: "meaningful",
    rarity: "uncommon",
  },
];

export const thePainThatMovedCardCase: CardCaseContent = {
  schemaVersion: "card-case-v1",
  contentVersion: "2.0.0-card-draft.1",
  caseId: CASE_ID,
  title: "The Pain That Moved",
  status: "medicalReviewRequired",
  patient: {
    id: "patient.jordan-lee",
    displayName: "Jordan Lee",
    age: 20,
    pronouns: "they/them",
    portraitKey: "patient.jordan-lee",
    introduction: "Jordan has felt sick and has had stomach pain since earlier today.",
  },
  disclaimer:
    "Meducktion is a fictional educational game. It is not medical advice, clinical training, or a diagnostic tool. Do not use it to make decisions about real patients.",
  correctConditionId: APPENDICITIS,
  conditions: [
    {
      id: APPENDICITIS,
      displayName: "Appendicitis",
      learnMore: "Inflammation of the appendix in this fictional case.",
      iconKey: "condition-appendix",
    },
    {
      id: STOMACH_INFECTION,
      displayName: "Stomach infection",
      learnMore: "An infection or inflammation affecting the stomach and intestines.",
      iconKey: "condition-stomach",
    },
    {
      id: URINARY_INFECTION,
      displayName: "Urinary infection",
      learnMore: "An infection involving part of the urinary tract.",
      iconKey: "condition-urinary",
    },
    {
      id: KIDNEY_STONE,
      displayName: "Kidney stone",
      learnMore: "A solid deposit that can cause strong pain near the urinary tract.",
      iconKey: "condition-kidney",
    },
  ],
  clues: [
    {
      id: "clue.pain-started-central",
      displayText: "The pain began near the middle of the stomach.",
      expandedText: "Several of the four choices can look like this at first.",
      supportsConditionIds: [APPENDICITIS, STOMACH_INFECTION],
      conflictsConditionIds: [],
      meaningful: true,
    },
    {
      id: "clue.pain-migrated-lower-right",
      displayText: "The pain moved to the lower-right side.",
      expandedText: "In this fictional case, that pattern makes appendicitis more likely.",
      supportsConditionIds: [APPENDICITIS],
      conflictsConditionIds: [STOMACH_INFECTION, URINARY_INFECTION, KIDNEY_STONE],
      meaningful: true,
    },
    {
      id: "clue.loss-of-appetite",
      displayText: "Jordan has little appetite.",
      expandedText: "This supports the leading pattern but does not prove it alone.",
      supportsConditionIds: [APPENDICITIS],
      conflictsConditionIds: [URINARY_INFECTION, KIDNEY_STONE],
      meaningful: true,
    },
    {
      id: "clue.no-diarrhea",
      displayText: "Jordan has not had diarrhea.",
      expandedText: "That makes the authored stomach-infection choice less convincing.",
      supportsConditionIds: [APPENDICITIS, URINARY_INFECTION, KIDNEY_STONE],
      conflictsConditionIds: [STOMACH_INFECTION],
      meaningful: true,
    },
    {
      id: "clue.no-urinary-symptoms",
      displayText: "Jordan has no burning or increased urinary frequency.",
      expandedText: "That weighs against the urinary-infection choice in this case.",
      supportsConditionIds: [APPENDICITIS, STOMACH_INFECTION],
      conflictsConditionIds: [URINARY_INFECTION],
      meaningful: true,
    },
    {
      id: "clue.lower-right-tenderness",
      displayText: "The lower-right stomach area is tender.",
      expandedText: "The location of the finding strengthens the appendicitis pattern.",
      supportsConditionIds: [APPENDICITIS],
      conflictsConditionIds: [STOMACH_INFECTION, URINARY_INFECTION],
      meaningful: true,
    },
    {
      id: "clue.mild-dehydration",
      displayText: "Jordan has mild signs of dehydration.",
      expandedText: "This is useful context, but it does not separate the answer choices well.",
      supportsConditionIds: [APPENDICITIS, STOMACH_INFECTION],
      conflictsConditionIds: [],
      meaningful: false,
    },
    {
      id: "clue.temperature-38",
      displayText: "Jordan has a mild fever.",
      expandedText: "Fever can go with inflammation or infection and needs other clues for context.",
      supportsConditionIds: [APPENDICITIS, STOMACH_INFECTION, URINARY_INFECTION],
      conflictsConditionIds: [KIDNEY_STONE],
      meaningful: true,
    },
    {
      id: "clue.pain-remains-localized",
      displayText: "The pain remains focused in the lower-right side.",
      expandedText: "Continued pain in this location strengthens the leading pattern.",
      supportsConditionIds: [APPENDICITIS],
      conflictsConditionIds: [STOMACH_INFECTION, URINARY_INFECTION],
      meaningful: true,
    },
    {
      id: "clue.white-count-elevated",
      displayText: "The blood test shows signs of inflammation.",
      expandedText: "Inflammation is present, but the source still matters.",
      supportsConditionIds: [APPENDICITIS, STOMACH_INFECTION, URINARY_INFECTION],
      conflictsConditionIds: [KIDNEY_STONE],
      meaningful: true,
    },
    {
      id: "clue.urinalysis-no-infection-support",
      displayText: "The urine test does not strongly suggest a urinary infection.",
      expandedText: "This weakens that choice without claiming a test can rule it out in real life.",
      supportsConditionIds: [APPENDICITIS, STOMACH_INFECTION, KIDNEY_STONE],
      conflictsConditionIds: [URINARY_INFECTION],
      meaningful: true,
    },
    {
      id: "clue.ultrasound-consistent-appendicitis",
      displayText: "The ultrasound shows a finding that supports appendicitis.",
      expandedText: "This is a strong authored clue when combined with the rest of the case.",
      supportsConditionIds: [APPENDICITIS],
      conflictsConditionIds: [STOMACH_INFECTION, URINARY_INFECTION, KIDNEY_STONE],
      meaningful: true,
    },
  ],
  cards,
  variants: [
    {
      id: VARIANT_ID,
      displayName: "Classic presentation",
      startingClueId: "clue.pain-started-central",
      initiallyStrongAlternativeId: STOMACH_INFECTION,
      especiallyValuableCardIds: [
        "card.ask.pain-movement",
        "card.check.abdomen",
        "card.test.ultrasound",
      ],
    },
  ],
  sharedEvents: [
    {
      id: "event.patient-remembers",
      displayName: "Patient Remembers",
      description: "Each player draws one Ask card.",
      effect: { type: "draw_category", category: "ask" },
    },
    {
      id: "event.second-look",
      displayName: "Second Look",
      description: "Each player replaces one card.",
      effect: { type: "replace_one" },
    },
    {
      id: "event.clear-signal",
      displayName: "Clear Signal",
      description: "Reveal one shared case clue.",
      effect: {
        type: "reveal_public_clue",
        clueId: "clue.pain-migrated-lower-right",
      },
    },
    {
      id: "event.helpful-nurse",
      displayName: "Helpful Nurse",
      description: "Each player draws two cards and keeps one.",
      effect: { type: "draw_two_keep_one" },
    },
  ],
  clueCollectorSet: [
    "clue.pain-migrated-lower-right",
    "clue.lower-right-tenderness",
    "clue.white-count-elevated",
  ],
  educationalExplanation:
    "Jordan's pain began near the middle and moved to the lower-right side. The focused tenderness and inflammation clues fit appendicitis better than the other choices in this fictional case.",
};
