import type { ActionDefinition, CaseDefinition, RuleCondition } from "../case-content/schemas/caseTypes";
import type { CaseCallSubmission, DifferentialUpdate, EngineError, GameCommand, GameEvent, GameOutcome, GameState, PendingTest, ScoreRuntimeState, TransitionResult } from "./types";
export type * from "./types";

const error = (code: EngineError["code"], message: string, relatedId?: string): TransitionResult => ({ state: null as never, events: [], errors: [{ code, message, ...(relatedId ? { relatedId } : {}) }] });
const copy = (state: GameState): GameState => structuredClone(state);

export function createInitialState(def: CaseDefinition): GameState {
  const revealedClues = def.clues.filter(c => c.initiallyVisible).map(c => ({ clueId: c.id, revealedInterval: 0, sourceId: "case_intro" }));
  const base: GameState = {
    caseId:def.caseId, variantId:def.variantId, schemaVersion:def.schemaVersion, contentVersion:def.contentVersion, phase:"case_intro", careInterval:1,
    maximumCareIntervals:def.mode.maximumCareIntervals, stability:def.patient.startingStability, startingStability:def.patient.startingStability,
    focusAvailable:0, careBudgetRemaining:def.mode.startingCareBudget, careBudgetSpent:0, selectedActions:[], lockedActionIds:[], completedActionIds:[], actionUseCounts:{}, pendingTests:[], revealedClues,
    revealedWarningIds:[], triggeredComplicationIds:[], differential:def.differential.map((d,i)=>({ diagnosisId:d.diagnosisId, rank:i+1, confidence:i===0?"plausible":"possible", evidence:[], mustExclude:def.diagnoses.find(x=>x.id===d.diagnosisId)?.mustExclude??false })),
    caseCallAttemptsUsed:0,lastCaseCall:null,escalated:false,complete:false,outcome:null,score:null,eventLog:[],revision:0,
  };
  const event: GameEvent={sequence:1,type:"case_created",careInterval:1,relatedIds:[def.caseId],payload:{schemaVersion:def.schemaVersion,contentVersion:def.contentVersion}};
  base.eventLog=[event]; return base;
}

function fail(state:GameState, code:EngineError["code"], message:string, relatedId?:string):TransitionResult { const r=error(code,message,relatedId); return {...r,state}; }
function emit(state:GameState, events:GameEvent[], type:string, ids:string[]=[], payload:Record<string,unknown>={}):void { events.push({sequence:state.eventLog.length+events.length+1,type,careInterval:state.careInterval,relatedIds:ids,payload}); }
function finish(state:GameState, events:GameEvent[], def:CaseDefinition, outcome:GameOutcome):void { state.complete=true;state.phase="case_complete";state.outcome=outcome;state.pendingTests=[];state.score=calculateScore(def,state);emit(state,events,"score_calculated",[],{total:state.score.total});emit(state,events,"case_completed",[],{outcome}); }
function done(original:GameState,state:GameState,events:GameEvent[]):TransitionResult { state.revision=original.revision+1;state.eventLog=[...original.eventLog,...events];return{state,events,errors:[]}; }

export function transitionGame(def:CaseDefinition, original:GameState, command:GameCommand):TransitionResult {
  if(original.complete) return fail(original,"CASE_ALREADY_COMPLETE","The case is already complete.");
  const state=copy(original), events:GameEvent[]=[];
  switch(command.type){
    case "START_CASE": if(state.phase!=="case_intro")return fail(original,"INVALID_PHASE","Case can only start from case_intro.");state.phase="planning";state.focusAvailable=def.mode.focusPerPlayerPerInterval;emit(state,events,"case_started");break;
    case "SELECT_ACTION": { if(state.phase!=="planning")return fail(original,"INVALID_PHASE","Actions may only be selected during planning.");const a=def.actions.find(x=>x.id===command.actionId);if(!a)return fail(original,"UNKNOWN_ACTION","Unknown action.",command.actionId);const validation=validateSelection(def,state,[...state.selectedActions.map(x=>x.actionId),a.id]);if(validation)return fail(original,validation.code,validation.message,validation.relatedId);state.selectedActions.push({actionId:a.id});emit(state,events,"action_selected",[a.id]);break; }
    case "DESELECT_ACTION": if(state.phase!=="planning")return fail(original,"INVALID_PHASE","Actions may only be deselected during planning.");if(!state.selectedActions.some(x=>x.actionId===command.actionId))return fail(original,"UNKNOWN_ACTION","Action is not selected.",command.actionId);state.selectedActions=state.selectedActions.filter(x=>x.actionId!==command.actionId);emit(state,events,"action_deselected",[command.actionId]);break;
    case "LOCK_ACTIONS": if(state.phase!=="planning")return fail(original,"INVALID_PHASE","Actions can only lock during planning.");{const v=validateSelection(def,state,state.selectedActions.map(x=>x.actionId));if(v)return fail(original,v.code,v.message,v.relatedId);state.lockedActionIds=[...state.selectedActions.map(x=>x.actionId)].sort();state.phase="actions_locked";emit(state,events,"actions_locked",state.lockedActionIds);}break;
    case "RESOLVE_INTERVAL": if(state.phase!=="actions_locked")return fail(original,"ACTIONS_NOT_LOCKED","Actions must be locked before resolution.");resolveInterval(def,state,events);break;
    case "ACKNOWLEDGE_RESULTS": if(state.phase!=="results_reveal")return fail(original,"INVALID_PHASE","Results are not awaiting acknowledgement.");state.phase="decision";emit(state,events,"results_acknowledged");break;
    case "CONTINUE_TO_NEXT_INTERVAL": if(state.phase!=="decision"||state.escalated)return fail(original,"INVALID_PHASE","Cannot continue now.");if(state.careInterval>=state.maximumCareIntervals){finish(state,events,def,"time_expired_failure");break;}state.careInterval++;state.phase="planning";state.focusAvailable=def.mode.focusPerPlayerPerInterval;state.selectedActions=[];state.lockedActionIds=[];emit(state,events,"interval_started");break;
    case "UPDATE_DIFFERENTIAL": {if(!["planning","decision"].includes(state.phase))return fail(original,"INVALID_PHASE","Differential cannot be updated now.");const e=validateDifferential(def,state,command.entries);if(e)return fail(original,e.code,e.message,e.relatedId);state.differential=command.entries.map(x=>({...x,mustExclude:def.diagnoses.find(d=>d.id===x.diagnosisId)?.mustExclude??false}));emit(state,events,"differential_updated");break;}
    case "SUBMIT_CASE_CALL": {if(state.phase!=="decision")return fail(original,"INVALID_PHASE","Case Calls require the decision phase.");const e=validateCaseCall(def,state,command.caseCall);if(e)return fail(original,e.code,e.message,e.relatedId);submitCall(def,state,events,command.caseCall);break;}
    case "COMPLETE_ESCALATED_UNRESOLVED": if(state.phase!=="decision"||!state.escalated)return fail(original,"INVALID_PHASE","Safe unresolved completion requires escalation.");finish(state,events,def,"safe_stabilization_without_diagnosis");break;
    default:return fail(original,"INVALID_COMMAND","Unknown command.");
  }
  return done(original,state,events);
}

function validateSelection(def:CaseDefinition,state:GameState,ids:string[]):EngineError|null {
  if(new Set(ids).size!==ids.length)return{code:"DUPLICATE_ACTION",message:"An action cannot be selected twice."};
  const actions=ids.map(id=>def.actions.find(a=>a.id===id));if(actions.some(a=>!a))return{code:"UNKNOWN_ACTION",message:"Unknown action."};const aa=actions as ActionDefinition[];
  if(aa.reduce((n,a)=>n+a.focusCost,0)>state.focusAvailable)return{code:"INSUFFICIENT_FOCUS",message:"Selection exceeds Focus."};
  if(aa.reduce((n,a)=>n+a.careBudgetCost,0)>state.careBudgetRemaining)return{code:"INSUFFICIENT_BUDGET",message:"Selection exceeds Care Budget."};
  for(const a of aa){if(a.repeatRule.type==="never"&&(state.completedActionIds.includes(a.id)||state.pendingTests.some(t=>t.actionId===a.id)))return{code:"ACTION_NOT_REPEATABLE",message:"Action is not repeatable.",relatedId:a.id};if(a.prerequisites&&!condition(a.prerequisites,state))return{code:"INVALID_COMMAND",message:"Prerequisite not satisfied.",relatedId:a.id};if(a.lockoutConditions?.some(c=>condition(c,state)))return{code:"INVALID_COMMAND",message:"Action is locked out.",relatedId:a.id};}
  const due=state.pendingTests.filter(t=>t.remainingDelay>1&&t.occupiesMajorSlot).length;const newMajor=aa.filter(a=>a.category==="test"&&a.occupiesMajorTestSlot).length;if(due+newMajor>def.mode.maximumPendingMajorTests)return{code:"TEST_QUEUE_FULL",message:"Major test queue is full."};return null;
}

function resolveInterval(def:CaseDefinition,state:GameState,events:GameEvent[]):void {
  state.phase="resolving";emit(state,events,"resolution_started");const locked=state.lockedActionIds.map(id=>def.actions.find(a=>a.id===id)).filter((a):a is ActionDefinition=>Boolean(a));
  for(const a of locked.filter(a=>a.category==="treatment"||a.category==="escalation")){if(a.category==="escalation"){state.escalated=true;emit(state,events,"case_escalated",[a.id]);}else{const use=state.actionUseCounts[a.id]??0;changeStability(state,events,a.stabilityEffectsByUse[use]??0,a.id);reveal(state,events,a.result.clueIds,a.id);}}
  const completed:PendingTest[]=[];for(const t of state.pendingTests){t.remainingDelay--;emit(state,events,"test_timer_advanced",[t.actionId],{remainingDelay:t.remainingDelay});if(t.remainingDelay===0)completed.push(t);}
  state.pendingTests=state.pendingTests.filter(t=>t.remainingDelay>0);
  for(const a of locked.filter(a=>a.category!=="treatment"&&a.category!=="escalation")){if(a.category==="test"){state.pendingTests.push({id:`${a.id}@${state.careInterval}`,actionId:a.id,orderedInterval:state.careInterval,remainingDelay:a.delayCareIntervals,completionInterval:null,resultClueIds:a.resultClueIds,occupiesMajorSlot:a.occupiesMajorTestSlot});emit(state,events,"test_ordered",[a.id],{delay:a.delayCareIntervals});}else if(a.result.type==="revealClues")reveal(state,events,a.result.clueIds,a.id);else{const range=a.result.ranges.find(r=>state.careInterval>=r.fromInterval&&state.careInterval<=r.toInterval);if(range)reveal(state,events,range.clueIds,a.id);}}
  for(const t of completed){reveal(state,events,t.resultClueIds,t.actionId);emit(state,events,"test_completed",[t.actionId]);}
  const stage=def.progression.stages.find(s=>s.interval===state.careInterval);if(stage&&!state.escalated){changeStability(state,events,stage.baselineStabilityDelta,stage.id);for(const d of stage.conditionalStabilityDeltas)if(condition(d.condition,state))changeStability(state,events,d.delta,d.id);}
  if(stage)for(const wid of stage.warningIds){const w=def.progression.warnings.find(x=>x.id===wid);if(w&&!state.revealedWarningIds.includes(w.id)&&condition(w.condition,state)){state.revealedWarningIds.push(w.id);emit(state,events,"warning_triggered",[w.id]);}}
  if(stage&&!state.escalated)for(const cid of stage.complicationIds){const c=def.progression.complications.find(x=>x.id===cid);if(c&&!state.triggeredComplicationIds.includes(c.id)&&condition(c.trigger,state)&&!condition(c.preventedBy,state)){state.triggeredComplicationIds.push(c.id);changeStability(state,events,c.stabilityDelta,c.id);reveal(state,events,c.revealClueIds,c.id);emit(state,events,"complication_triggered",[c.id]);}}
  for(const a of locked){state.actionUseCounts[a.id]=(state.actionUseCounts[a.id]??0)+1;if(!state.completedActionIds.includes(a.id))state.completedActionIds.push(a.id);}const spent=locked.reduce((n,a)=>n+a.careBudgetCost,0);state.careBudgetSpent+=spent;state.careBudgetRemaining-=spent;state.focusAvailable=0;state.selectedActions=[];state.phase="results_reveal";emit(state,events,"results_revealed");
  if(state.stability<=0)finish(state,events,def,"critical_failure");
}
function changeStability(state:GameState,events:GameEvent[],delta:number,source:string):void{if(delta===0)return;const prev=state.stability;state.stability=Math.max(0,Math.min(state.startingStability,state.stability+delta));emit(state,events,"stability_changed",[source],{source,previous:prev,delta:state.stability-prev,next:state.stability});}
function reveal(state:GameState,events:GameEvent[],ids:string[],source:string):void{for(const id of ids)if(!state.revealedClues.some(c=>c.clueId===id)){state.revealedClues.push({clueId:id,revealedInterval:state.careInterval,sourceId:source});emit(state,events,"clue_revealed",[id,source]);}}
function condition(c:RuleCondition,state:GameState):boolean{switch(c.type){case"intervalAtLeast":return state.careInterval>=c.value;case"intervalEquals":return state.careInterval===c.value;case"stabilityAtOrBelow":return state.stability<=c.value;case"actionCompleted":return state.completedActionIds.includes(c.actionId);case"actionNotCompleted":return!state.completedActionIds.includes(c.actionId);case"clueRevealed":return state.revealedClues.some(x=>x.clueId===c.clueId);case"testPending":return state.pendingTests.some(x=>x.actionId===c.actionId);case"caseEscalated":return state.escalated;case"all":return c.conditions.every(x=>condition(x,state));case"any":return c.conditions.some(x=>condition(x,state));case"not":return!condition(c.condition,state);}}

function validateDifferential(def:CaseDefinition,state:GameState,entries:DifferentialUpdate[]):EngineError|null{if(entries.length!==def.differential.length||new Set(entries.map(e=>e.diagnosisId)).size!==entries.length||new Set(entries.map(e=>e.rank)).size!==entries.length||entries.map(e=>e.rank).sort((a,b)=>a-b).some((r,i)=>r!==i+1))return{code:"INVALID_DIFFERENTIAL",message:"Ranks must be unique and contiguous."};const allowed=new Set(def.differential.map(d=>d.diagnosisId));for(const e of entries){if(!allowed.has(e.diagnosisId))return{code:"INVALID_DIFFERENTIAL",message:"Unknown diagnosis.",relatedId:e.diagnosisId};for(const x of e.evidence)if(!state.revealedClues.some(c=>c.clueId===x.clueId))return{code:"UNREVEALED_CLUE",message:"Differential evidence is not revealed.",relatedId:x.clueId};}return null;}
function validateCaseCall(def:CaseDefinition,state:GameState,c:CaseCallSubmission):EngineError|null{if(state.caseCallAttemptsUsed>=def.mode.caseCallAttemptLimit)return{code:"CASE_CALL_ATTEMPTS_EXHAUSTED",message:"No attempts remain."};if(!c.diagnosisId||!c.urgency||!c.nextStepId||c.supportingClueIds.length<def.caseCall.minimumSupportingClues||!c.alternativeDiagnosisId||!c.alternativeWeakeningClueId)return{code:"INCOMPLETE_CASE_CALL",message:"Case Call is incomplete."};if(c.alternativeDiagnosisId===c.diagnosisId)return{code:"INCOMPLETE_CASE_CALL",message:"Alternative must differ."};if(!def.diagnoses.some(d=>d.id===c.diagnosisId)||!def.diagnoses.some(d=>d.id===c.alternativeDiagnosisId)||!def.nextSteps.some(n=>n.id===c.nextStepId))return{code:"INCOMPLETE_CASE_CALL",message:"Diagnosis or next step is invalid."};const revealed=new Set(state.revealedClues.map(x=>x.clueId));for(const id of [...c.supportingClueIds,c.alternativeWeakeningClueId])if(!revealed.has(id))return{code:"UNREVEALED_CLUE",message:"Case Call cites unrevealed evidence.",relatedId:id};const clues=c.supportingClueIds.map(id=>def.clues.find(x=>x.id===id));if(clues.some(x=>!x?.relationships.some(r=>r.diagnosisId===c.diagnosisId&&r.direction==="supports")))return{code:"INCOMPLETE_CASE_CALL",message:"Supporting evidence is irrelevant."};if(new Set(clues.map(x=>x?.category)).size<def.caseCall.minimumEvidenceCategories)return{code:"INCOMPLETE_CASE_CALL",message:"Supporting evidence needs more categories."};const alt=def.clues.find(x=>x.id===c.alternativeWeakeningClueId);if(!alt?.relationships.some(r=>r.diagnosisId===c.alternativeDiagnosisId&&r.direction==="conflicts"))return{code:"INCOMPLETE_CASE_CALL",message:"Alternative weakening evidence is irrelevant."};return null;}
function submitCall(def:CaseDefinition,state:GameState,events:GameEvent[],c:CaseCallSubmission):void{state.caseCallAttemptsUsed++;const correct=c.diagnosisId===def.finalAnswer.diagnosisId&&c.urgency===def.finalAnswer.urgency&&c.nextStepId===def.finalAnswer.nextStepId;state.lastCaseCall={...c,correct,submittedInterval:state.careInterval};emit(state,events,"case_call_submitted",[c.diagnosisId]);if(correct){emit(state,events,"case_call_correct");finish(state,events,def,calculateOutcome(state));return;}emit(state,events,"case_call_incorrect");const unsafe=c.diagnosisId==="diagnosis.nonspecific-abdominal-pain"&&def.clues.some(cl=>cl.redFlag.isRedFlag&&state.revealedClues.some(r=>r.clueId===cl.id))&&def.nextSteps.find(n=>n.id===c.nextStepId)?.urgency==="routine";if(unsafe||state.caseCallAttemptsUsed>=def.mode.caseCallAttemptLimit){finish(state,events,def,"incorrect_diagnosis");return;}if(state.careInterval>=state.maximumCareIntervals){finish(state,events,def,"time_expired_failure");return;}state.careInterval++;const stage=def.progression.stages.find(s=>s.interval===state.careInterval);if(stage&&!state.escalated){changeStability(state,events,stage.baselineStabilityDelta,stage.id);for(const d of stage.conditionalStabilityDeltas)if(condition(d.condition,state))changeStability(state,events,d.delta,d.id);}state.phase="decision";if(state.stability<=0)finish(state,events,def,"critical_failure");}
function calculateOutcome(state:GameState):GameOutcome{if(state.stability<=40)return"correct_poor_outcome";if(state.careBudgetRemaining>=5&&state.careInterval<=3)return"excellent_resolution";if(state.careBudgetRemaining===0)return"correct_but_inefficient";return"safe_resolution";}
export function calculateScore(def:CaseDefinition,state:GameState):ScoreRuntimeState{const c=def.scoring.categories,call=state.lastCaseCall;const correct=call?.correct??false;const penalties:Array<{id:string;points:number}>=[];const diagnosis=state.outcome==="safe_stabilization_without_diagnosis"?c.diagnosis.safeWithoutDiagnosis:correct?(state.caseCallAttemptsUsed===1?c.diagnosis.correctFirstAttempt:c.diagnosis.correctAfterOneIncorrect):0;if(correct&&state.caseCallAttemptsUsed>1)penalties.push({id:"incorrect-case-call",points:-c.diagnosis.firstIncorrectCall});const safety=c.safety.stabilityBandsDescending.find(b=>state.stability>=b.minimumValue)?.points??0;let reasoning=0;if(correct&&call){reasoning=Math.min(c.reasoning.supportingCluePointsMaximum,call.supportingClueIds.length*c.reasoning.pointsPerValidSupportingClue);const cats=new Set(call.supportingClueIds.map(id=>def.clues.find(x=>x.id===id)?.category));if(cats.size>=2)reasoning+=c.reasoning.categoryDiversityPoints;reasoning+=c.reasoning.validAlternativePoints+c.reasoning.weakeningEvidencePoints+(call.classificationsCorrect===false?0:c.reasoning.correctClassificationPoints);}const urgencyAndNextStep=state.outcome==="safe_stabilization_without_diagnosis"&&state.escalated?150:(call?(call.urgency===def.finalAnswer.urgency?75:0)+(call.nextStepId===def.finalAnswer.nextStepId?75:0):0);const completed=state.completedActionIds.map(id=>def.actions.find(a=>a.id===id)).filter((a):a is ActionDefinition=>Boolean(a));const counted=completed.filter(a=>!(c.efficiency.treatmentActionsExempt&&(a.category==="treatment"||a.category==="escalation")));const low=counted.filter(a=>a.efficiency==="lowValue").length*c.efficiency.lowValuePenalty;const waste=counted.filter(a=>a.efficiency==="wasteful").length*c.efficiency.wastefulPenalty;if(low)penalties.push({id:"low-value-actions",points:-low});if(waste)penalties.push({id:"wasteful-actions",points:-waste});let efficiency=c.efficiency.basePoints+state.careBudgetRemaining*c.efficiency.pointsPerUnusedBudget-low-waste;const major=def.actions.filter(a=>a.category==="test"&&a.occupiesMajorTestSlot);if(major.every(a=>state.completedActionIds.includes(a.id))){efficiency-=c.efficiency.allMajorTestsOrderedPenalty;penalties.push({id:"all-major-tests-ordered",points:-c.efficiency.allMajorTestsOrderedPenalty});}efficiency=Math.max(0,Math.min(c.efficiency.maximum,efficiency));const speedAndCoordination=c.speedAndCoordination.pointsByTerminalInterval[state.careInterval]??0;const values={diagnosis,safety,reasoning:Math.min(150,reasoning),urgencyAndNextStep,efficiency,speedAndCoordination};const total=Math.max(0,Math.min(1000,Object.values(values).reduce((a,b)=>a+b,0)));return{...values,penalties,total};}

export const selectors={selectedFocus:(d:CaseDefinition,s:GameState)=>s.selectedActions.reduce((n,x)=>n+(d.actions.find(a=>a.id===x.actionId)?.focusCost??0),0),selectedBudget:(d:CaseDefinition,s:GameState)=>s.selectedActions.reduce((n,x)=>n+(d.actions.find(a=>a.id===x.actionId)?.careBudgetCost??0),0),provisionalFocus:(d:CaseDefinition,s:GameState)=>s.focusAvailable-selectors.selectedFocus(d,s),provisionalBudget:(d:CaseDefinition,s:GameState)=>s.careBudgetRemaining-selectors.selectedBudget(d,s),pendingMajorSlots:(d:CaseDefinition,s:GameState)=>d.mode.maximumPendingMajorTests-s.pendingTests.filter(t=>t.occupiesMajorSlot).length,stabilityLabel:(s:GameState)=>s.stability===0?"failure":s.stability<=25?"critical":s.stability<=50?"unstable":s.stability<=75?"guarded":"stable",canLock:(s:GameState)=>s.phase==="planning",canOpenCaseCall:(s:GameState)=>s.phase==="decision",mayContinue:(s:GameState)=>s.phase==="decision"&&!s.escalated&&s.careInterval<s.maximumCareIntervals};
