import { describe, expect, it } from "vitest";
import { thePainThatMoved as def } from "../case-content/cases/thePainThatMoved";
import { calculateScore, createInitialState, selectors, transitionGame } from "../game-engine";
import type { CaseCallSubmission, GameCommand, GameState } from "../game-engine";

function command(state:GameState, cmd:GameCommand):GameState { const r=transitionGame(def,state,cmd);expect(r.errors).toEqual([]);return r.state; }
function start():GameState{return command(createInitialState(def),{type:"START_CASE"});}
function interval(state:GameState, actions:string[]):GameState{for(const actionId of actions)state=command(state,{type:"SELECT_ACTION",actionId});state=command(state,{type:"LOCK_ACTIONS"});state=command(state,{type:"RESOLVE_INTERVAL"});if(state.phase==="case_complete")return state;return command(state,{type:"ACKNOWLEDGE_RESULTS"});}
function next(state:GameState):GameState{return command(state,{type:"CONTINUE_TO_NEXT_INTERVAL"});}
const strongCall=(supportingClueIds:string[],alternativeDiagnosisId:string,alternativeWeakeningClueId:string):CaseCallSubmission=>({diagnosisId:"diagnosis.appendicitis",urgency:"urgent",nextStepId:"next-step.urgent-surgical-assessment",supportingClueIds,alternativeDiagnosisId,alternativeWeakeningClueId});

describe("initial state and immutable transitions",()=>{
  it("pins versions and approved starting values",()=>{const intro=createInitialState(def);expect(intro).toMatchObject({phase:"case_intro",careInterval:1,stability:82,careBudgetRemaining:8,focusAvailable:0,schemaVersion:1,contentVersion:"1.0.0-draft.1"});expect(intro.revealedClues).toHaveLength(4);expect(intro.differential).toHaveLength(5);const planned=start();expect(planned.focusAvailable).toBe(2);expect(intro.phase).toBe("case_intro");});
  it("does not mutate case content",()=>{const before=JSON.stringify(def);interval(start(),["action.history.pain-movement"]);expect(JSON.stringify(def)).toBe(before);});
});

describe("selection, locking, and resolution",()=>{
  it("selects and deselects without applying effects",()=>{let s=start();s=command(s,{type:"SELECT_ACTION",actionId:"treatment.supportive-fluids"});expect(s.stability).toBe(82);expect(s.careBudgetRemaining).toBe(8);expect(selectors.provisionalFocus(def,s)).toBe(1);s=command(s,{type:"DESELECT_ACTION",actionId:"treatment.supportive-fluids"});expect(selectors.provisionalBudget(def,s)).toBe(8);});
  it("rejects Focus overflow, unknown actions, duplicates, and wrong phases",()=>{let s=start();s=command(s,{type:"SELECT_ACTION",actionId:"test.abdominal-ultrasound"});expect(transitionGame(def,s,{type:"SELECT_ACTION",actionId:"action.history.appetite"}).errors[0]?.code).toBe("INSUFFICIENT_FOCUS");expect(transitionGame(def,start(),{type:"SELECT_ACTION",actionId:"missing"}).errors[0]?.code).toBe("UNKNOWN_ACTION");expect(transitionGame(def,s,{type:"SELECT_ACTION",actionId:"test.abdominal-ultrasound"}).errors[0]?.code).toBe("DUPLICATE_ACTION");expect(transitionGame(def,createInitialState(def),{type:"LOCK_ACTIONS"}).errors[0]?.code).toBe("INVALID_PHASE");});
  it("locks separately from resolution and spends only on resolution",()=>{let s=start();s=command(s,{type:"SELECT_ACTION",actionId:"test.blood-count"});s=command(s,{type:"LOCK_ACTIONS"});expect(s.phase).toBe("actions_locked");expect(s.careBudgetRemaining).toBe(8);s=command(s,{type:"RESOLVE_INTERVAL"});expect(s.phase).toBe("results_reveal");expect(s.careBudgetRemaining).toBe(6);expect(s.pendingTests[0]?.remainingDelay).toBe(1);});
  it("allows zero-action resolution",()=>{const s=interval(start(),[]);expect(s.stability).toBe(80);});
});

describe("tests, treatments, progression",()=>{
  it("advances existing tests before queueing new tests and completes two together",()=>{let s=interval(start(),["test.blood-count","test.urinalysis"]);s=next(s);s=interval(s,["test.abdominal-ultrasound"]);expect(s.pendingTests).toHaveLength(1);expect(s.revealedClues.some(c=>c.clueId==="clue.white-count-elevated")).toBe(true);expect(s.revealedClues.some(c=>c.clueId==="clue.urinalysis-no-infection-support")).toBe(true);expect(s.pendingTests[0]?.remainingDelay).toBe(2);});
  it("applies diminishing treatments and the stability ceiling",()=>{let s=interval(start(),["treatment.supportive-fluids"]);expect(s.stability).toBe(80);s=next(s);s=interval(s,["treatment.supportive-fluids"]);expect(s.stability).toBe(78);});
  it("triggers warnings before later consequences",()=>{let s=start();s=interval(s,[]);s=next(s);s=interval(s,[]);s=next(s);s=interval(s,[]);expect(s.revealedWarningIds).toContain("warning.delay-unsafe");s=next(s);s=interval(s,[]);expect(s.revealedWarningIds).toContain("warning.complication-imminent");});
  it("triggers the late complication once",()=>{let s=start();for(let i=1;i<=5;i++){s=interval(s,[]);if(i<5)s=next(s);}expect(s.triggeredComplicationIds).toEqual(["complication.progressive-peritoneal-irritation"]);expect(s.stability).toBe(30);});
  it("escalation stops current progression",()=>{const s=interval(start(),["action.safety.urgent-escalation"]);expect(s.stability).toBe(82);expect(s.escalated).toBe(true);expect(selectors.mayContinue(s)).toBe(false);});
});

describe("differential and Case Calls",()=>{
  it("accepts a valid differential and preserves Must Exclude",()=>{let s=interval(start(),["action.history.pain-movement"]);const entries=s.differential.map((e,i)=>({diagnosisId:e.diagnosisId,rank:i+1,confidence:e.confidence,evidence:i===0?[{clueId:"clue.pain-migrated-lower-right",direction:"supports" as const}]:[]}));s=command(s,{type:"UPDATE_DIFFERENTIAL",entries});expect(s.differential.find(e=>e.diagnosisId==="diagnosis.appendicitis")?.mustExclude).toBe(true);});
  it("rejects duplicate ranks and unrevealed evidence",()=>{const s=interval(start(),[]);const entries=s.differential.map(e=>({diagnosisId:e.diagnosisId,rank:1,confidence:e.confidence,evidence:[]}));expect(transitionGame(def,s,{type:"UPDATE_DIFFERENTIAL",entries}).errors[0]?.code).toBe("INVALID_DIFFERENTIAL");const valid=s.differential.map((e,i)=>({diagnosisId:e.diagnosisId,rank:i+1,confidence:e.confidence,evidence:i===0?[{clueId:"clue.mild-guarding",direction:"supports" as const}]:[]}));expect(transitionGame(def,s,{type:"UPDATE_DIFFERENTIAL",entries:valid}).errors[0]?.code).toBe("UNREVEALED_CLUE");});
  it("rejects incomplete and unrevealed Case Calls",()=>{const s=interval(start(),[]);const incomplete=strongCall(["clue.nausea"],"diagnosis.gastroenteritis","clue.no-diarrhea");expect(transitionGame(def,s,{type:"SUBMIT_CASE_CALL",caseCall:incomplete}).errors[0]?.code).toBe("INCOMPLETE_CASE_CALL");const hidden=strongCall(["clue.pain-migrated-lower-right","clue.lower-right-tenderness"],"diagnosis.gastroenteritis","clue.no-diarrhea");expect(transitionGame(def,s,{type:"SUBMIT_CASE_CALL",caseCall:hidden}).errors[0]?.code).toBe("UNREVEALED_CLUE");});
});

describe("approved paper paths",()=>{
  it("Path A: efficient intended path scores 965",()=>{let s=start();s=interval(s,["action.history.pain-movement","action.examination.focused-abdomen"]);expect(s.stability).toBe(80);s=next(s);s=interval(s,["test.blood-count","treatment.supportive-fluids"]);expect(s.stability).toBe(78);expect(s.pendingTests).toHaveLength(1);s=next(s);s=interval(s,["action.history.diarrhea","action.safety.urgent-escalation"]);expect(s.pendingTests).toHaveLength(0);s=command(s,{type:"SUBMIT_CASE_CALL",caseCall:strongCall(["clue.pain-migrated-lower-right","clue.lower-right-tenderness"],"diagnosis.gastroenteritis","clue.no-diarrhea")});expect(s.outcome).toBe("excellent_resolution");expect(s.score?.total).toBe(965);});
  it("Path B: test spam scores 810",()=>{let s=start();s=interval(s,["test.blood-count","test.urinalysis"]);expect(s.stability).toBe(80);s=next(s);s=interval(s,["test.abdominal-ultrasound"]);expect(s.stability).toBe(76);s=next(s);s=interval(s,["action.examination.hydration","action.monitoring.vital-signs"]);expect(s.stability).toBe(70);s=next(s);expect(transitionGame(def,s,{type:"SELECT_ACTION",actionId:"treatment.symptom-support"}).errors[0]?.code).toBe("INSUFFICIENT_BUDGET");s=interval(s,["action.monitoring.pain"]);expect(s.stability).toBe(58);s=next(s);s=interval(s,["action.safety.urgent-escalation"]);s=command(s,{type:"SUBMIT_CASE_CALL",caseCall:strongCall(["clue.ultrasound-consistent-appendicitis","clue.white-count-elevated"],"diagnosis.urinary-tract-infection","clue.urinalysis-no-infection-support")});expect(s.outcome).toBe("correct_but_inefficient");expect(s.score?.total).toBe(810);});
  it("Path C: premature-call recovery scores 835",()=>{let s=start();s=interval(s,[]);s=command(s,{type:"SUBMIT_CASE_CALL",caseCall:{diagnosisId:"diagnosis.gastroenteritis",urgency:"urgent",nextStepId:"next-step.urgent-surgical-assessment",supportingClueIds:["clue.nausea","clue.temperature-38"],alternativeDiagnosisId:"diagnosis.nonspecific-abdominal-pain",alternativeWeakeningClueId:"clue.temperature-38"}});expect(s.careInterval).toBe(2);expect(s.stability).toBe(76);s=next(s);s=interval(s,["action.history.pain-movement","action.examination.focused-abdomen"]);s=next(s);s=interval(s,["treatment.supportive-fluids","action.safety.urgent-escalation"]);expect(s.stability).toBe(74);s=command(s,{type:"SUBMIT_CASE_CALL",caseCall:strongCall(["clue.pain-migrated-lower-right","clue.lower-right-tenderness"],"diagnosis.gastroenteritis","clue.pain-migrated-lower-right")});expect(s.score?.total).toBe(835);});
  it("Path D: safety-first unresolved scores 655",()=>{let s=start();s=interval(s,["treatment.supportive-fluids","action.monitoring.vital-signs"]);s=next(s);s=interval(s,["action.safety.urgent-escalation","treatment.symptom-support"]);expect(s.stability).toBe(82);s=command(s,{type:"COMPLETE_ESCALATED_UNRESOLVED"});expect(s.outcome).toBe("safe_stabilization_without_diagnosis");expect(s.score?.total).toBe(655);expect(calculateScore(def,s)).toEqual(s.score);});
});
